# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: acac4ad5bd1f3200e73883ae6ddc87e49ffc70d45e4ac118c9d87f762efbbc25351db9507adae3b2b38f875b7ade5b8def05996767c795ea6846191bea557466

test:
  secret_key_base: 736a1a57b788af87ea2656b8f7684ee265cdd9cf316b85e37dba7b309c0ed96b1bd199815b7d71f2b00c1a850ca9275484bee752c1aac5a69b43f8a5f5ee76d4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
